---
- hosts: all
  gather_facts: False
  roles:
    - vmware.coreos-bootstrap

- name: install k8s
  hosts: all
  become: yes
  tasks:

    - name: enable docker service
      systemd: name=docker state=started enabled=yes

    - name: create dir for CNI plugins
      file: path=/opt/cni/bin state=directory recurse=yes

    - name: install CNI plugins
      unarchive:
        src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-amd64-v{{ cni_version }}.tgz
        dest: /opt/cni/bin
        creates: /opt/cni/bin/loopback
        remote_src: yes

    - name: create dir for k8s binaries
      file: path=/opt/bin state=directory recurse=yes

    - name: install k8s binaries
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/{{ item }}
        dest: /opt/bin
        mode: 0555
      with_items:
        - kubeadm
        - kubelet
        - kubectl

    - name: create kubelet config
      get_url:
        url: https://raw.githubusercontent.com/kubernetes/kubernetes/v{{ k8s_version }}/build/debs/kubelet.service
        dest: /etc/systemd/system/kubelet.service
      notify: change kubelet config path

    - name: create dir for kubeadm conf
      file: path=/etc/systemd/system/kubelet.service.d state=directory recurse=yes

    - name: create kubeadm config
      get_url:
        url: https://raw.githubusercontent.com/kubernetes/kubernetes/v{{ k8s_version }}/build/debs/10-kubeadm.conf
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      notify: change kubeadm config path

    - name: enable kubelet service
      systemd: name=kubelet state=started enabled=yes

  handlers: 

    - name: change kubelet config path
      replace:
        path: /etc/systemd/system/kubelet.service
        regexp: /usr/bin
        replace: /opt/bin

    - name: change kubeadm config path
      replace:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        regexp: /usr/bin
        replace: /opt/bin
